name: laundry_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  curved_navigation_bar: ^1.0.6
  lottie: ^2.2.0  # Corrected indentation here
  webview_flutter: ^4.0.0
  flutter_inappwebview: ^5.3.0
  flutter_webview_plugin: ^0.4.0
  flutter_html: 3.0.0-beta.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/banner_1.jpg
    - assets/img/banner_2.jpg
    - assets/img/banner_3.jpg
    - assets/img/cloth-washing.jpg
    - assets/img/cloth-iron.jpg
    - assets/img/cloth-washing-folding.jpg
    - assets/img/dry-cleaning.jpg
    - assets/img/logo.png
    - assets/img/splashscreen2.png
    - assets/img/splashscreen3.png
    - assets/img/login-bg.jpg
    - assets/img/signup-bg.jpg
    - assets/img/profile-avatar.png
    - assets/img/jean.png
    - assets/img/shirt.png
    - assets/img/t-shirt.png
    - assets/img/track-pants.webp
    - assets/img/saree.png 
    - assets/img/girl-sthirt.webp 
    - assets/img/forgetpassword-bg.webp
    - assets/img/resetpasswrod-bg.webp
    - assets/img/animation-confirm.json
